server:
  port: 9001
  servlet:
    context-path: /shiro
spring:
  application:
    name: shiro-action
  main:
    banner-mode: off
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/cloud_action?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp
  thymeleaf:
    prefix: /html/
    suffix: .html
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.aladdin.shiro.entity
photo:
  upload:
    path: http://115.159.235.96:8888/group1/upload
  delete:
    path: http://115.159.235.96:8888/group1/upload
management:
  endpoints:
    web:
      exposure:
        include: "*"