server:
  port: 8805
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
spring:
  application:
    name: rabbit-producer

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  rabbitmq:
    # \u96C6\u7FA4\u5730\u5740\uFF0C\u7528\u9017\u53F7\u5206\u9694
    addresses: 127.0.0.1:15672
    connection-timeout: 15000
    password: guest
    username: guest
    # \u4F7F\u7528\u542F\u7528\u6D88\u606F\u786E\u8BA4\u6A21\u5F0F
    #    publisher-confirms: true
    virtual-host: /


