server:
  port: 8805
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
spring:
  application:
    name: rabbitmq-producer
  main:
    banner-mode: off
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  rabbitmq:
    connection-timeout: 20000
    password: admin
    username: admin
    virtual-host: /cloud-action
    host:
    port: 5672
    publisher-confirm-type: correlated
#    publisher-confirm-type: correlated


