server:
  port: 8805
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
spring:
  application:
    name: rabbitmq-producer
  main:
    banner-mode: off
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
    time-zone: GMT+8
  rabbitmq:
    username: gopher
    password: gopher
    virtual-host: gopher_vh
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 10
        prefetch: 1
    addresses: 115.159.235.37,115.159.235.12,115.159.235.96

